### PR TITLE
[merged] [cat-29] added 4

### PR DESCRIPTION
**Pull request by whence**

### CODE REVIEW

**Comment by whence** [comment]
@canva-merge has merged test-feature-44 into main as <a href="https://github.com/whence/go-cat/commit/fb9f460eedb419efff54e69318a5e73102e6ec44">fb9f460</a>.

<details>
<summary>To revert</summary>

````md
:rocket:[canva-revert-pr]
````

This will create a revert PR.

If you need the revert PR to be yolo merged

````md
:rocket:[canva-revert-pr]

```ini
YOLO=true
YOLO_REASON=<reason>
```
````
</details>

**Comment by whence** [comment]
hello comment

**Comment by merge-service** [comment]
hello comment

**Comment by whence** [comment]
hello comment

**Comment by whence** [comment]
hello comment

**Pull request closed without merging**
